

// Generated by Selenium IDE

import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCase{
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeClass
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "C:\\Users\\swath\\eclipse-workspace\\Newproj\\Drivers\\chromedriver.exe " );
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterClass
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test() {
    driver.get("https://www.hyrtutorials.com/p/basic-controls.html");
    //driver.manage().window().setSize(new Dimension(1895, 1018));
    
    driver.manage().window().maximize();
    js.executeScript("window.scrollTo(0,28)");
    driver.findElement(By.id("firstName")).sendKeys("swa");
    driver.findElement(By.id("lastName")).click();
    driver.findElement(By.id("lastName")).sendKeys("ts");
    driver.findElement(By.id("femalerb")).click();
    driver.findElement(By.cssSelector(".basicControls")).click();
    driver.findElement(By.id("englishchbx")).click();
    driver.findElement(By.id("hindichbx")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("swathiupadhyats@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234");
    driver.findElement(By.id("registerbtn")).click();
  }
}
